[window.dimensions]
columns = 130
lines = 42

[colors.cursor]
cursor = "0xc5c8c6"
text = "0x1d1f21"

[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[font]
size = 10.0

[font.bold]
family = "hack"
style = "Bold"

[font.italic]
family = "hack"
style = "Italic"

[font.normal]
family = "hack"
style = "Regular"

[shell]
program = "/bin/Shell"
